name: monadcount

services:
  api:
    image: ghcr.io/sibyx/monadcount-api:master
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      PGHOST: timescaledb
      PGUSER: postgres
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: monadcount
      PGPORT: 5432
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      DATA_DIR: /var/monad
    volumes:
      - monad-storage:/var/monad
    networks:
      monadcount-network:
        ipv4_address: 172.20.1.2

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: monadcount
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    networks:
      monadcount-network:
        ipv4_address: 172.20.1.3

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - timescaledb
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    networks:
      monadcount-network:
        ipv4_address: 172.20.1.4

volumes:
  timescaledb-data:
  grafana-storage:
  monad-storage:

networks:
  monadcount-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
