name: monadcount-local

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - timescaledb-data:/home/postgres/pgdata/data
    ports:
      - "5433:5432"

  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - ./data/logs/clickhouse:/var/log/clickhouse-server/
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ports:
      - "8123:8123" # HTTP interface
      - "8124:9000" # Native client

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - timescaledb
      - clickhouse
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"

volumes:
  timescaledb-data:
  grafana-storage:
  clickhouse-data:
