name: monadcount

services:
  api:
    image: ghcr.io/sibyx/monadcount-api:master
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      PGHOST: timescaledb
      PGUSER: postgres
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: monadcount
      PGPORT: 5432
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      DATA_DIR: /var/monad
      SENTRY_DSN: ${SENTRY_DSN}
    volumes:
      - monad-storage:/var/monad
      - ./logs:/var/log
    networks:
      intranet:
        ipv4_address: 172.28.1.2

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: monadcount
    volumes:
      - timescaledb-data:/home/postgres/pgdata/data
    networks:
      intranet:
        ipv4_address: 172.28.1.3

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - timescaledb
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    networks:
      intranet:
        ipv4_address: 172.28.1.4

volumes:
  timescaledb-data:
  grafana-storage:
  monad-storage:

networks:
  intranet:
    # docker network create --driver=bridge --subnet=172.28.0.0/16 --gateway=172.28.0.1 monadcount
    name: monadcount
    external: true
