name: monadcount

services:
  postgresql:
    image: postgis/postgis:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      intranet:
        ipv4_address: 172.28.10.1

  redis:
    image: "redis:7"
    command: redis-server
    volumes:
      - redis-storage:/data
    environment:
      REDIS_REPLICATION_MODE: master
    networks:
      intranet:
        ipv4_address: 172.28.10.2

  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - ./logs/clickhouse:/var/log/clickhouse-server/
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ports:
      - "8123:8123" # HTTP interface
      - "8124:9000" # Native client
    networks:
      intranet:
        ipv4_address: 172.28.1.3

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - postgresql
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    networks:
      intranet:
        ipv4_address: 172.28.10.4

  api:
    image: ghcr.io/sibyx/monadcount-api:master
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      PGHOST: postgresql
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: 5432
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      DATA_DIR: /var/monad
      SENTRY_DSN: ${SENTRY_DSN}
      REDIS_URL: redis://172.28.10.2/0
    volumes:
      - monad-storage:/var/monad
      - ./logs/api:/var/log
    networks:
      intranet:
        ipv4_address: 172.28.20.1

  worker:
    image: ghcr.io/sibyx/monadcount-api:master
    depends_on:
      - redis
      - clickhouse
    environment:
      PGHOST: timescaledb
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: 5432
      AUTH_USERNAME: ${AUTH_USERNAME}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      DATA_DIR: /var/monad
      SENTRY_DSN: ${SENTRY_DSN}
      REDIS_URL: redis://172.28.10.2/0
    volumes:
      - monad-storage:/var/monad
      - ./logs:/var/log
    command: /usr/local/bin/python3 -m dramatiq monadcount_api.tasks:create_broker monadcount_api.tasks --processes 5 --threads 8
    networks:
      intranet:
        ipv4_address: 172.28.20.2

volumes:
  postgresql-data:
  grafana-storage:
  monad-storage:
  redis-storage:
  clickhouse-data:

networks:
  intranet:
    # docker network create --driver=bridge --subnet=172.28.0.0/16 --gateway=172.28.0.1 monadcount
    name: monadcount
    external: true
