"""structures

Revision ID: 1991d238d8e2
Revises: 1caaff97db57
Create Date: 2024-11-24 22:06:54.704066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "1991d238d8e2"
down_revision: Union[str, None] = "1caaff97db57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "structures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.Enum("room", "wall", name="structuretype"), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON", srid=998999, spatial_index=False, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_structures_geom", "structures", ["geom"], unique=False, postgresql_using="gist", postgresql_ops={}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(
        "idx_structures_geom", table_name="structures", postgresql_using="gist", column_name="geom"
    )
    op.drop_geospatial_table("structures")
    # ### end Alembic commands ###
