"""Measurements

Revision ID: 1caaff97db57
Revises: 45b1dc6ee262
Create Date: 2024-11-19 23:36:28.163251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1caaff97db57"
down_revision: Union[str, None] = "45b1dc6ee262"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("uploaded_file_id", sa.Integer(), nullable=True),
        sa.Column("happened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("additional_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.mac_address"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_file_id"],
            ["uploaded_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("measurements")
    # ### end Alembic commands ###
