"""UploadedFile refactor

Revision ID: 45b1dc6ee262
Revises: f753a3e060f5
Create Date: 2024-11-13 23:38:41.880648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from monadcount_api.db import UploadedFile

# revision identifiers, used by Alembic.
revision: str = "45b1dc6ee262"
down_revision: Union[str, None] = "f753a3e060f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("measurements", if_exists=True)
    op.add_column("uploaded_files", sa.Column("version", sa.Integer(), nullable=True))
    op.execute("UPDATE uploaded_files SET version = 1;")
    op.alter_column("uploaded_files", "version", nullable=False)
    op.add_column("uploaded_files", sa.Column("happened_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("uploaded_files", sa.Column("additional_data", sa.JSON(), nullable=True))
    op.alter_column("uploaded_files", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("uploaded_files", "created_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.alter_column(
        "uploaded_files",
        "file_type",
        existing_type=sa.Enum("csip", "l2pk", name="filetype"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("uploaded_files", "additional_data")
    op.drop_column("uploaded_files", "happened_at")
    op.drop_column("uploaded_files", "version")
    # ### end Alembic commands ###
