"""UploadedFile size

Revision ID: d63936aaa65c
Revises: 1991d238d8e2
Create Date: 2024-11-26 16:14:50.827206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d63936aaa65c"
down_revision: Union[str, None] = "1991d238d8e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("uploaded_files", sa.Column("filesize", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uploaded_files", "filesize")
    # ### end Alembic commands ###
